config/routes.rb
Rails.application.routes.draw do
  get     '/login',   to: 'sessions#new'
  post    '/signup',  to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  delete  '/users',   to: 'users#destroy'
  get     '/logout',  to: 'sessions#new'
  get     '/signup',  to: 'users#new'
  resources :posts
  resources :users
  resources :pages
  resources :settings
  root 'blog#blog'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
  has_rich_text :root_page_content
  # validate :only_one

  # private

  # def only_one
  #   if Setting.count >= 1
  #     errors.add :base, 'There can only be one global setting'
  #   end
  # end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update ]

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
    @setting = Setting.find(params[:id])
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # setting /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:blog_title, :blog_sub_title, :root_page_name,
                                      :root_page_content, :root_page_posts, :root_page_menu)
    end
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>

  <div>
    <%= form.label :blog_title %>
    <%= form.text_area :blog_title %>
  </div>

  <div>
    <%= form.label :blog_sub_title %>
    <%= form.text_area :blog_sub_title %>
  </div>

  <div>
    <%= form.label :root_page_menu %>
    <%= form.check_box :root_page_menu %>
  </div>

  <div>
    <%= form.label :root_page_posts %>
    <%= form.check_box :root_page_posts %>
  </div>

  <div>
    <%= form.label :root_page_name %>
    <%= form.text_area :root_page_name %>
  </div>

  <div>
    <%= form.label :root_page_content %>
    <%= form.rich_text_area :root_page_content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<% if logged_in? %>
<h1>Editing Settings</h1>
<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>
<% else %>
<%= render 'Show' %>
<% end %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>
<% if logged_in? %>
<h1>Settings</h1>

<% if Setting.any? %>
  <table>
    <thead>
      <tr>
        <th>Blog title</th>
        <th>Blog sub title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @settings.each do |setting| %>
        <tr>
          <td><%= setting.blog_title %></td>
          <td><%= setting.blog_sub_title %></td>
          <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= link_to 'Setup blog', new_setting_path %>
<% end %>
<br>

<% else %>
<%#  TODO: redirect to 404 %>
<% end %>

app/views/settings/new.html.erb
<% if logged_in? %>
  <h1>New Setting</h1>
  <%= render 'form', setting: @setting %>
  <%= link_to 'Back', settings_path %>
<% else %>
<% end %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <h1>
    <%= @setting.blog_title %>
  </h1>

  <div>
    <%= @setting.blog_sub_title %>
  </div>

</div>
<% if logged_in? %>
  <%= link_to 'Edit', edit_setting_path(@setting) %> |
  <%= link_to 'Back', settings_path %>
<% else %>
<% end %>