config/routes.rb
Rails.application.routes.draw do
  get     '/login',   to: 'sessions#new'
  post    '/signup',  to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  delete  '/users',   to: 'users#destroy'
  get     '/logout',  to: 'sessions#new'
  get     '/signup',  to: 'users#new'
  resources :posts
  resources :users
  resources :pages
  resources :settings
  root 'blog#blog'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_menu.html.erb
<nav>
  <% if logged_in? %>
    <%= link_to "Profile", current_user %>
    <%= link_to "Settings", settings_path %>
    <%= link_to "Posts", posts_path %>
    <%= link_to "Pages", pages_path %>
    <%= link_to "Log out", logout_path, method: :delete %>
  <% else %>
  <% end %>
</nav>

app/views/layouts/_footer.html.erb
<footer>
  <p>Build with <a href="http://blogonrails.org" target="_blank">Blog on Rails</a></p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= render 'layouts/admin_menu' %>
  <% if Setting.any? %>
    <h1><%= Setting.first.blog_title %></h1>
    <div><%= Setting.first.blog_sub_title %></div>
  <% else %>
    <h1>Your new blog</h1>
    <div>You can modify this in settings</div>
  <% end %>
  <%= render 'layouts/menu' %>
</header>

app/views/layouts/_menu.html.erb
<%= debug(params) if Rails.env.development? %>
<nav>
  <% if Setting.first.root_page_name.present? || Setting.first.root_page_menu? %>
    <% if Setting.first.root_page_menu? %>
      <%= link_to Setting.first.root_page_name, root_path %>
    <% else %>
    <% end %>
  <% else %>
  <% end %>
  <% Page.all.where('pages.active = ?', true).order(sort: :asc).each do |page| %>
    <%= link_to page.title, page %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>